
spring:
  application:
    name: projetoApiDeVendasEmSpring
  flyway:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/projeto_api_de_vendas_em_spring?options=-c%20TimeZone=UTC
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        jdbc :
          time_zone : UTC
  mvc:
    servlet:
      path: /api
  jwt:
    secret-key: ${JWT_KEY}
    expiration: 1800000

