
spring:
  application:
    name: projetoApiDeVendasEmSpring
  flyway:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/projeto_api_de_vendas_em_spring?options=-c%20TimeZone=UTC
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        jdbc :
          time_zone : UTC
